run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions and types

    # Additional recommended linters
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Spell checker
    - revive        # Metalinter with many useful rules
    - gocritic      # Opinionated Go source code linter
    - gocyclo       # Computes cyclomatic complexity
    - gosec         # Security checker
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - stylecheck    # Replacement for golint
    - prealloc      # Find slice declarations that could be preallocated
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - godot         # Check comments end in period
    - whitespace    # Check for unnecessary whitespace
    - errorlint     # Find code that will cause problems with error wrapping
    - exhaustive    # Check exhaustiveness of enum switch statements

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  stylecheck:
    checks: ["all"]

  godot:
    scope: declarations

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unparam
